### ISSUE TITLE
Compilation problems when trying to use axum 0.7

### ISSUE THREAD

**Issue by bastibense** [Totodore/socketioxide#186]
Probably a dup of #182.

I just updated to the latest stable axum 0.7 and now I get a compilation error when I try to use the layer with axum (see code snippet below).

**Describe the bug**
Can't compile with socketioxide and axum 0.7.

**To Reproduce**

```
#[tokio::main]
async fn main() {
  ...
    let (layerx, io) = SocketIo::new_layer();

    // Set up the HTTP server.
    let app: Router = Router::new()
        ...
        .merge(blocks_medias::routes::routes())
        .layer(layerx)
        .layer(DefaultBodyLimit::max(1024 * 1024 * 200))
        .with_state(state);

    let listener = tokio::net::TcpListener::bind("0.0.0.0:3000").await.unwrap();
    axum::serve(listener, app).await.unwrap();
}

```

**Compiler error:**

```
error[E0277]: the trait bound `SocketIoService<Route>: tower_service::Service<axum::http::Request<axum::body::Body>>` is not satisfied
   --> src/main.rs:78:16
    |
78  |         .layer(layerx)
    |          ----- ^^^^^^ the trait `tower_service::Service<axum::http::Request<axum::body::Body>>` is not implemented for `SocketIoService<Route>`
    |          |
    |          required by a bound introduced by this call
    |
    = help: the trait `tower_service::Service<http::request::Request<ReqBody>>` is implemented for `SocketIoService<S, A>`
note: required by a bound in `Router::<S>::layer`
   --> /Users/bbense/.cargo/registry/src/index.crates.io-6f17d22bba15001f/axum-0.7.1/src/routing/mod.rs:236:21
    |
233 |     pub fn layer<L>(self, layer: L) -> Router<S>
    |            ----- required by a bound in this associated function
...
236 |         L::Service: Service<Request> + Clone + Send + 'static,
    |                     ^^^^^^^^^^^^^^^^ required by this bound in `Router::<S>::layer`


```

**Versions (please complete the following information):**
 - Socketioxide version: head and 0.7.2
 - axum 0.7

**Comment by Totodore** [comment]
Yes, it is indeed related to the migration to hyper 1.0.
The problem is that Salvo is working with v1-rc* and it didn't migrate yet.
Therefore I have to drop support for salvo if I want to migrate (which I might do if their migration to stable hyper is taking too long)

**Comment by Totodore** [comment]
Salvo is only a Dev dep used for examples inside the socketioxide lib

**Comment by Totodore** [comment]
Salvo is another http framework like axum so migrating to hyper 1.0 will break the compatibility
